// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XRClarkSignalR.Api.Hubs.Model;

#nullable disable

namespace XRClarkSignalR.Api.Migrations
{
    [DbContext(typeof(XrclarkContext))]
    partial class XrclarkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("XRClarkSignalR.Api.Hubs.Model.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("MachineMass")
                        .HasColumnType("REAL");

                    b.Property<double>("MachineMaxHeight")
                        .HasColumnType("REAL");

                    b.Property<double>("MachineMaxWeight")
                        .HasColumnType("REAL");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("MachinePower")
                        .HasColumnType("REAL");

                    b.Property<double>("MachineSpeed")
                        .HasColumnType("REAL");

                    b.Property<double>("MachineTension")
                        .HasColumnType("REAL");

                    b.Property<double>("MachineWheels")
                        .HasColumnType("REAL");

                    b.HasKey("MachineId");

                    b.ToTable("Machines");
                });
#pragma warning restore 612, 618
        }
    }
}
